<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default scoreboard</name>
  <uuid>b5f0ab84-5dd1-4120-9f10-db2c8250393a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[If 'ML model invocation' is in error 
then 
set decision to a new Scoreboard where
		the Confidence is 0, 
		High risk is true , 
		the Segment is "unknown" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
