<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>get machine learning output</name>
  <uuid>47a4c56c-dd88-4cef-aa2a-64e69f07eb36</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
set percent to the maximum score of 'ML model invocation';
if the predictions of 'ML model invocation' is 1
then 
set decision to a new Scoreboard where
		the Confidence is percent, 
		High risk is true , 
		the Segment is "Unknown" ;
else
set decision to a new Scoreboard where 
	the Confidence is percent , 
	the Segment is "Unknown" , 
	High risk is false; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
